## List of the beginner level question and answering

### 1. Temperature Data Analyzer

In [1]:
import numpy as np

In [23]:
days_list = np.random.randint(30, 40, 30)

mean = np.mean(days_list)
max_val = np.max(days_list)
min_val = np.min(days_list)
std = np.std(days_list)

mask = days_list > mean


print(days_list)
print(f"Mean of the 1 month temp: {mean}")
print(f"Max temp in 1 month: {max_val}")
print(f"Min temp in 1 month: {min_val}")
print(f"standard deviation: {std:.2f}")

print(f"list of hot days: {days_list[mask]}")






[37 36 31 37 31 37 39 32 35 32 36 37 30 38 35 35 33 30 31 33 32 32 33 32
 33 32 33 37 32 34]
Mean of the 1 month temp: 33.833333333333336
Max temp in 1 month: 39
Min temp in 1 month: 30
standard deviation: 2.50
list of hot days: [37 36 37 37 39 35 36 37 38 35 35 37 34]


### 2. Student Grades System

In [50]:
marks = [
    [85, 90, 78, 92],  
    [88, 76, 95, 89], 
    [91, 82, 87, 90]   
]

print("====== Math, English, Science, History =======")
for i, student in enumerate(marks, start=1):
    print(f"Student {i} marks: {student}")
    
    
totals = np.sum(marks, axis=1)
averages = np.mean(marks, axis=1)

for i, (t, a) in enumerate(zip(totals, averages), start=1):
    print(f"Student {i} → Total: {t}, Average: {a:.2f}")
    
highest_score = np.max(marks, axis=0)
topper = np.argmax(marks, axis=0)

for subj, (score, topper) in enumerate(zip(highest_score, topper), start=1):
    print(f"Subject {subj} → Highest Score: {score}, Topper: Student {topper+1}")

#Use sorting to rank students by total score.

totals = np.sum(marks, axis=1)
ranking = np.argsort(-totals)

for rank, idx in enumerate(ranking, start=1):
    print(f"Rank {rank}: Student {idx+1} → Total = {totals[idx]} ")




====== Math, English, Science, History =======
Student 1 marks: [85, 90, 78, 92]
Student 2 marks: [88, 76, 95, 89]
Student 3 marks: [91, 82, 87, 90]
Student 1 → Total: 345, Average: 86.25
Student 2 → Total: 348, Average: 87.00
Student 3 → Total: 350, Average: 87.50
Subject 1 → Highest Score: 91, Topper: Student 3
Subject 2 → Highest Score: 90, Topper: Student 1
Subject 3 → Highest Score: 95, Topper: Student 2
Subject 4 → Highest Score: 92, Topper: Student 1
Rank 1: Student 3 → Total = 350 
Rank 2: Student 2 → Total = 348 
Rank 3: Student 1 → Total = 345 


### 3. Image Manipulation (Grayscale)

In [54]:
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],     # Row 1 (Red, Green, Blue)
    [[255, 255, 0], [0, 255, 255], [255, 0, 255]], # Row 2 (Yellow, Cyan, Magenta)
    [[100, 100, 100], [200, 200, 200], [50, 50, 50]] # Row 3 (Shades of gray)
])

print("Original RGB image:\n", image)

grayscale = np.dot(image[...,:3], [0.2989, 0.5870, 0.1140])
print("\nGrayscale image:\n", np.round(grayscale, 2))

Original RGB image:
 [[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [  0 255 255]
  [255   0 255]]

 [[100 100 100]
  [200 200 200]
  [ 50  50  50]]]

Grayscale image:
 [[ 76.22 149.68  29.07]
 [225.9  178.76 105.29]
 [ 99.99 199.98  50.  ]]


### 4. Dice Rolling Simulator

In [ ]:
num_rolls = 20

rolls = np.random.randint(1,7, num_rolls)

values, counts = np.unique(rolls, return_counts=True)

averages = (counts / num_rolls) * 100

print("Dice rolls:", rolls)
print("\nFrequencies & Percentages:")

for v, c, p in zip(values, counts, averages):
     print(f"{v} → {c} time(s), {p:.2f}%")

ValueError: too many values to unpack (expected 2)