## Intermediate NumPy Project Ideas

In [1]:
import numpy as np

### 1. Image Processing (Grayscale & Color)

### 2. Weather Data Simulation & Analysis

In [32]:
np.random.seed(400)
weathers = np.random.randint(30, 40, 15).reshape(5,3)

print("Weather per city")
cities = ["Peshawar", "Lahor", "Islamabad"]
days = ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"]

print('  ',' '.join(cities))
for i, row in enumerate(weathers):
    print(days[i], " → ", " ".join(map(str, row)))

mean = np.mean(weathers)
print(f"Average of these days: {mean:.2f}°C")

hottest_day = np.max(weathers)
print(f"Hottest Day: {hottest_day}°C")

coldest_day = np.min(weathers)
print(f"Coldest Day: {coldest_day}°C")

variation = np.std(weathers)
print(f"Variation between Days: {variation:.2f}")

mask = weathers > 35
print(f"days above 35°C: {weathers[mask]}")

hottestPerDay = np.max(weathers, axis=1)
print(hottestPerDay)



Weather per city
   Peshawar Lahor Islamabad
Day 1  →  39 33 37
Day 2  →  36 35 38
Day 3  →  36 36 32
Day 4  →  31 37 31
Day 5  →  35 32 37
Average of these days: 35.00°C
Hottest Day: 39°C
Coldest Day: 31°C
Variation between Days: 2.50
days above 35°C: [39 37 36 38 36 36 37 37]
[39 38 36 37 37]



### 3. Dice & Probability Simulator

In [61]:
rolls_dice = 30

rolls = np.random.randint(1,7, rolls_dice)

values, counts = np.unique(rolls, return_counts=True)

percentage = (counts / rolls_dice) * 100

print(rolls)


for v, c, p in zip(values, counts, percentage):
    print(f"{v}: {c} time(s) {p:.1f}%")



[3 6 1 4 3 5 5 3 3 3 1 3 1 4 3 2 3 2 5 5 6 2 3 6 2 4 1 4 3 6]
1: 4 time(s) 13.3%
2: 4 time(s) 13.3%
3: 10 time(s) 33.3%
4: 4 time(s) 13.3%
5: 4 time(s) 13.3%
6: 4 time(s) 13.3%


### 4. Stock Market Analysis

In [76]:
np.random.seed(400)
closing_prices = np.random.randint(530, 905, 10)

print(closing_prices)

daily_changes = np.diff(closing_prices)
print(f"Daily Changes: ", daily_changes)

average = np.mean(closing_prices)
print(f"Average Rate: {average}")

total_sum = np.cumsum(closing_prices)
print(total_sum)

total_sum = np.cumprod(closing_prices)
print(total_sum)




[878 848 670 792 775 666 637 721 728 557]
Daily Changes:  [ -30 -178  122  -17 -109  -29   84    7 -171]
Average Rate: 727.2
[ 878 1726 2396 3188 3963 4629 5266 5987 6715 7272]
[                 878               744544            498844480
         395084828160      306190741824000   203923034054784000
   771764176930546688  3039649355637613568  -744557940963516416
 -8890403495068508160]


### 5. Mini Recommender System

In [ ]:
np.random.seed(400)
rating = np.random.randint(1,6, 16).reshape(4,4)

print(rating)

print('Item1', 'Item2', 'Item3', 'Item4',)
users = ['User1', 'User2', 'User3', 'User4']

for i, row in enumerate(rating):
    print(days[i], " → ", " ".join(map(str, row)))
average_row = np.mean(rating, axis=0)
print(average_row)

[[5 2 5 4]
 [1 4 4 3]
 [2 2 3 5]
 [4 2 3 5]]
Item1 Item2 Item3 Item4
Day 1  →  5 2 5 4
Day 2  →  1 4 4 3
Day 3  →  2 2 3 5
Day 4  →  4 2 3 5
[3.   2.5  3.75 4.25]


### 6. Matrix & Linear Algebra Projects

In [92]:
import numpy as np

np.random.seed(400)


matrix = np.random.randint(1, 10, 16).reshape(4, 4)
print("Matrix:\n", matrix)


transpose = matrix.T
print("\nTranspose:\n", transpose)


determinant = np.linalg.det(matrix)
print("\nDeterminant:", determinant)

if determinant != 0:
    inverse = np.linalg.inv(matrix)
    print("\nInverse:\n", inverse)
else:
    print("\nMatrix is singular (no inverse possible)")


Matrix:
 [[4 8 7 6]
 [9 7 7 3]
 [2 8 2 6]
 [3 8 6 5]]

Transpose:
 [[4 9 2 3]
 [8 7 8 8]
 [7 7 2 6]
 [6 3 6 5]]

Determinant: -260.00000000000017

Inverse:
 [[ 0.11538462  0.15384615  0.09615385 -0.34615385]
 [-0.61538462  0.04615385  0.05384615  0.64615385]
 [ 0.15384615 -0.06153846 -0.23846154  0.13846154]
 [ 0.73076923 -0.09230769  0.14230769 -0.79230769]]
