##Numpy array and basic
learn about numpy with wih

In [2]:
import numpy as np

In [3]:

arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D Array:", arr_1d)
print("1D Array:", arr_2d)
print("1D Array:", arr_3d)


1D Array: [1 2 3 4 5]
1D Array: [[1 2 3]
 [4 5 6]]
1D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
import random
print("Random Integer: ", random.randint(1, 100))

list = random.sample(range(1, 100), 10)
print("Random Float: ", list)

Random Integer:  26
Random Float:  [46, 40, 35, 41, 86, 96, 68, 54, 1, 98]


NumPy Array Indexing


In [5]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr[2])

3


Access 2-D Arrays

In [6]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

print(arr[0,2])  # access the element of the first row and second third 

3


Access 3-D Arrays

In [7]:
import numpy as np

arr = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(arr[0,1,2])  #Access the third element of the second array of the first array:

6


NumPy Array Slicing

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1:4])

[2 3 4]


with step


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4,5,6,7,8,9,10])

print(arr[1:10:2])

[ 2  4  6  8 10]


Slicing 2-D Arrays

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


Vertor, Matrix, Tensor

In [12]:
vector = np.array([1,2,3,4,5])

print("Vector:", vector)

Vector: [1 2 3 4 5]


Matrix


In [13]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

print("Matrix:\n", matrix)

Matrix:
 [[1 2 3]
 [4 5 6]]


Tensor

In [21]:
tensor = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print("Tensor:\n", tensor.shape)  # Reshaping to 2x2x2 for better visualization

Tensor:
 (2, 2, 2)
