Numpy array operations

In [4]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Slicing in array

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 8, 9, 10])

print('Sliced array: ', arr[1: 7])

Sliced array:  [2 3 4 5 6 8]


2D slicing

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

print('2D Sliced array: ', arr[1, 0:3])  # Slicing a 2D array

2D Sliced array:  [4 5 6]


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('2D Sliced array: ', arr[0:2, 1])

2D Sliced array:  [2 5]


Sorted in array


In [9]:
arr = np.array([1, 7, 3, 9, 5])

print("Original array: ", arr)
print("Sorted in array: ", np.sort(arr))

Original array:  [1 7 3 9 5]
Sorted in array:  [1 3 5 7 9]


2D sorted array

In [10]:
arr = np.array([[2,4,3], [1,6,2]])

print("2D sorted array column: ", np.sort(arr, axis=0))

2D sorted array column:  [[1 4 2]
 [2 6 3]]


###Filter in array

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('Filtered array:', arr[arr > 5])

Filtered array: [6 7 8 9]


Mark array

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filtered_arr = arr[arr % 2 == 0]
print('Filtered even numbers:', filtered_arr)

Filtered even numbers: [ 2  4  6  8 10]


In [13]:
mask = np.array([1,2,3,4,5,6,7,8,9,10])

filtered_arr = mask > 5

print("Filtered array with mask: ", mask[filtered_arr])



Filtered array with mask:  [ 6  7  8  9 10]


In [15]:
condition_arr = np.where(mask > 5, mask*2, mask)

print("Conditionally modified array: ", condition_arr)

Conditionally modified array:  [ 1  2  3  4  5 12 14 16 18 20]


Array combination

In [16]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined_arr = np.concatenate((arr1, arr2))
print("Combined array: ", combined_arr)

Combined array:  [1 2 3 4 5 6]


Compatability check

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

print("Compatibility check: ", np.array_equal(arr1, arr2))


Compatibility check:  False


adding removing elements 

In [19]:
arr = np.array([1, 2, 3, 4, 5])

print("Original array: ", arr)

Original array:  [1 2 3 4 5]


In [20]:
arr = np.array([[1,2,3], [4,5,6]])
add_new_row = np.array([7, 8, 9])

arrAfter_new_row = np.vstack((arr, add_new_row))

print("Array after adding new row: ", arrAfter_new_row)
print("original array: ", arr)



Array after adding new row:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
original array:  [[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[1,2], [4,5]])

new_col = np.array([[9],[8]])

arrAfter_new_col = np.hstack((arr, new_col))

print("Array after adding new col: ", arrAfter_new_col)
print("original array: ", arr)

Array after adding new row:  [[1 2 9]
 [4 5 8]]
original array:  [[1 2]
 [4 5]]


In [29]:
arr = np.array([1, 2, 3, 4, 5])

deleted_element = np.delete(arr, 2)

print(deleted_element)

[1 2 4 5]
