PRACTICE TO NUMPY

In [4]:
import numpy as np

indexing of array Access 1-D Arrays / Access 2-D Arrays / Access 3-D Arrays

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[2])

3


In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:7])

[2 3 4 5 6 7]


2-D Array

In [7]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr[1, 2])

6


3-D Array

In [8]:
arr = np.array([[[1,2,3], [3,4,5]], [[6,7,8], [11,22,33]]])

print(arr[0, 1, 1])

4


In [9]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(arr[0, 1, 2])

6


NEGATIVE INDEXING

In [10]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-1])

7


In [11]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr[0,-2])

2


NumPy Array Slicing

In [18]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1 : 8])

[2 3 4 5 6 7 8]


In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[1: 8: 2])

[2 4 6 8]


In [25]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr[0:3, 0:3])

[[1 2 3]
 [4 5 6]]


In [30]:
arr = np.array([[1,2,3], [4,5,6], [6,7,8]])

print(arr[:3, :2])

[[1 2]
 [4 5]
 [6 7]]


    VIEW AND COPY

copy return new array and view just view the original array don't change the original array

In [32]:
arr = np.array([1,2,3,4,5])

x = arr.copy()
arr[1]= 30

print(arr)
print(x)

[ 1 30  3  4  5]
[1 2 3 4 5]


make view array it does effect on the original array when we change the view array and when we change the original array it effect the view array

In [36]:
arr = np.array([1,2,3,4,5,6,7,8])

x = arr.view()
arr[4] = 40

print(arr)
print(x)

[ 1  2  3  4 40  6  7  8]
[ 1  2  3  4 40  6  7  8]


SHAPE IN ARRAY

In [40]:
arr = np.array([1,2,3,4,5,6])

print(arr.shape)

(6,)


In [41]:
arr = np.array([[1,2,3], [4,6,7]])

print(arr.shape)


(2, 3)


In [42]:
arr = np.array([[[1,2,3], [4,5,6], [6,7,8]]])

print(arr.shape)

(1, 3, 3)


RESHAPE IN ARRAY

this is classed plattein we have more fun to rearranging the shape and element of the shape..

In [43]:
arr = np.array([[1,2,3], [4,5,6]])

print(arr.reshape(-1))

[1 2 3 4 5 6]


JOINING OF ARRAY

In [49]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

res = np.concatenate((arr1, arr2))
print(res)

[1 2 3 4 5 6]


In [55]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


SPLIT IN ARRAY

In [56]:
arr = np.array([1,2,3,4,5,6])

res = np.array_split(arr, 2)
print(res)

[array([1, 2, 3]), array([4, 5, 6])]
