#### everything with compusX

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,4])
arr2 = np.array([[1,2,3,4], [6,7,8,9]])
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [4]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4])

### changing array

In [5]:
print(arr1.dtype)

int64


In [6]:
arr1.astype(np.int32)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 4], dtype=int32)

### Array operation

#### scalar operator

In [7]:
res = arr2 * 2
print(res)

[[ 2  4  6  8]
 [12 14 16 18]]


#### vector operator

In [8]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [4,5,6]])
print(a1)
print(a2)

print((a1 + a2))

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [4 5 6]]
[[ 8 10 12]
 [ 8 10 12]]


In [9]:

arr = np.random.random((3,3))
arr = np.round(arr * 100)
print(arr)

[[86. 90. 76.]
 [98. 66. 54.]
 [59. 60.  6.]]


### max, min, sum, prod

In [10]:
np.max(arr1)

np.int64(9)

In [11]:
np.max(arr2)

np.int64(9)

In [12]:
np.min(arr1)

np.int64(1)

In [13]:
np.sum(arr1)

np.int64(49)

In [14]:
np.prod(arr1)

np.int64(1451520)

In [15]:
np.prod(arr2, axis=1)

array([  24, 3024])

### mean, median

In [16]:
np.mean(arr1)

np.float64(4.9)

In [17]:
np.median(arr1)

np.float64(4.5)

### dot product

the dot product is possible when the 4x3 and 3x4 something like this the first matrix column and the second matrix row equal then possible otherwise not possible ...

In [18]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12).reshape(4,3)

np.dot(a1, a2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

## Round, floor, ceil

In [19]:
arr = np.random.random(1)
print(arr * 10)


arr = np.round(arr * 10)

print(arr)

[9.02845028]
[9.]


In [20]:
arr = np.random.random(1)
print(arr * 10)

arr = np.floor(arr * 10)

print(arr)

[0.5239056]
[0.]


In [21]:
arr = np.random.random(1)
print(arr * 10)

arr = np.ceil(arr * 10)

print(arr)

[1.42065012]
[2.]


### indexing and slicing

#### indexing

In [22]:
print(arr1[2])

3


In [23]:
print(arr2[1, 2])

8


In [24]:
print(arr3[1, 1, 2])

12


### slicing

In [25]:
print(arr1[1:7])

[2 3 4 5 6 7]


In [26]:
print(arr2[:, :2])

[[1 2]
 [6 7]]


In [27]:
print(arr3[1:, 1:, 1:])

[[[11 12]]]


In [28]:
for i in arr1:
    print(i)

1
2
3
4
5
6
7
8
9
4


In [29]:
for i in arr2:
    print(i)

[1 2 3 4]
[6 7 8 9]


In [30]:
for i in arr3:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [31]:
for i in np.nditer(arr3):
    print(i)
    

1
2
3
4
5
6
7
8
9
10
11
12


### Reshaping 

#### Transpose 

In [32]:

print(arr2.T)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]


ravel

In [33]:
print(arr2.ravel())

[1 2 3 4 6 7 8 9]


### Stacking

In [34]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([5,4,6,4,5,6])

np.vstack((a1, a2))

array([[1, 2, 3, 4, 5, 6],
       [5, 4, 6, 4, 5, 6]])

In [35]:
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6, 5, 4, 6, 4, 5, 6])

### spliting

In [36]:
a2 = np.array([[1,2,3], [3,4,5], [6,5,4]])

res = np.hsplit(arr2, 2)
print(res)

[array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]])]


## advance indexing

advance indexing mean when we play with the multi-dimensional array then we need to advance indexing concept two types 1. fancy 2. boolean

#### Fancy

In [46]:
arr = np.arange(24).reshape(6,4)

res = [1,2,5]

print(arr[res])

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]]


In [ ]:
arr = np.arange(24).reshape(6,4)

res = [1,2,5]

print(arr[:, [res]])